//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncDataCalibration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public byte[] GUID { get; set; }
        public string Name { get; set; }
        public Nullable<long> IsDelete { get; set; }
        public string DateDelete { get; set; }
        public string DateModify { get; set; }
    
        public virtual ProductLine ProductLine { get; set; }
    }
}
